### ISSUE TITLE
Add login/sign up page

### ISSUE THREAD

**Issue by stephennemeth** [acm-uga/openSourceSpring23#31]

**Comment by williamsirotkin** [comment]
I'll add the UI for the page and the routes to navigate between the homepage and the login page

**Comment by AshwinkumarPillai** [comment]
I just saw this thread.
I added the UI in Figma
I have created Routes in App.js and created the login component.

**Comment by williamsirotkin** [comment]
Great work! I happened to work on the same feature as you, however I preferred your user interface and I liked how you had the fields integrated as a form. I merged your changes with mine onto the main branch, and resolved the conflicts by keeping my Routing within App.js, and using your CSS and JSX code for the login. Just something to keep in mind - make sure you comment on these Github tickets before you start working, so we can prevent working on the same feature!

**Comment by AshwinkumarPillai** [comment]
Thanks.
Yes I will make sure to comment before I start working from now on :)

**Comment by stephennemeth** [comment]
Im working on the sign up page part that the Create Account button directs to, will be mapped to the /register endpoint. I want to get this done before #30 is done. It will be easier to test out that way I believe

**Comment by stephennemeth** [comment]
This is done
