### ISSUE TITLE
Create Homepage Navbar (Different from Marketplace Nav Bar which is already created)

### ISSUE THREAD

**Issue by williamsirotkin** [acm-uga/openSourceSpring23#49]

**Comment by jdhubb99** [comment]
I'll start working on this - Jake Hubbard

I'll try my best to make it a version of these designs 👇

![Screenshot 2023-02-11 at 17 20 04](https://user-images.githubusercontent.com/49132883/218283498-2de9304b-ccea-4a42-81b1-ea98e739a281.jpg)
![Screenshot 2023-02-11 at 17 20 37](https://user-images.githubusercontent.com/49132883/218283505-0ce281e0-e782-4258-a069-2c7bffe2ea59.jpg)

**Comment by jwaryold2** [comment]
i'll try to help if you are not finished @jdhubb99 - Jason Waryold

**Comment by jdhubb99** [comment]
@jwaryold2 yeah for sure. I'm going to create a PR for my progress so far so you take a look

**Comment by stephennemeth** [comment]
This is done.
